services:
    bitbag_sylius_wishlist_plugin.checker.product_in_stock_checker:
        class: BitBag\SyliusWishlistPlugin\Checker\ProductInStockChecker
        arguments:
            - "@session.flash_bag"
            - '@translator'