services:
    BitBag\SyliusWishlistPlugin\Controller\Action\ApiPlatform\RemoveProductFromWishlistAction:
        arguments:
            - "@api_platform.message_bus"
        tags:
            - { name: controller.service_arguments }
    BitBag\SyliusWishlistPlugin\Controller\Action\ApiPlatform\RemoveProductVariantFromWishlistAction:
        arguments:
            - "@api_platform.message_bus"
        tags:
            - { name: controller.service_arguments }
