services:
    bitbag.sylius_wishlist_plugin.resolver.user_wishlist_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\ShopUserWishlistResolver
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist"

    bitbag.sylius_wishlist_plugin.resolver.anonymous_wishlist_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\AnonymousWishlistResolver
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist"
