services:
    bitbag.sylius_wishlist_plugin.updater.wishlist.wishlist_updater:
        class: BitBag\SyliusWishlistPlugin\Updater\WishlistUpdater
        arguments:
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
