services:
    bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductToWishlistAction
        arguments:
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist_product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "%wishlist_cookie_id%"

    bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveProductFromWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"

    bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ListWishlistProductsAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@templating.engine.twig"

    bitbag_sylius_wishlist_plugin.controller.action.render_header_template:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RenderHeaderTemplateAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@templating.engine.twig"

    bitbag_sylius_wishlist_plugin.context.wishlist:
        class: BitBag\SyliusWishlistPlugin\Context\WishlistContext
        arguments:
            - "@security.token_storage"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "%wishlist_cookie_id%"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist.inner"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistProductFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist_product
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product.inner"
